
[profile.dev]
opt-level = "z"

[profile.release]
opt-level = "z"

[workspace]
resolver ="2"
members = ["crates/rzomes/*", "crates/zomes/*"]

[workspace.dependencies]
#holochain = "0.1.4"
hdi = "=0.2"
hdk = "=0.1"
serde = "1"

[workspace.dependencies.invitations_integrity]
path = "crates/zomes/invitations"

[workspace.dependencies.profiles_integrity]
path = "crates/zomes/profiles"